# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiexinprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiexinprofile',
            name='cell',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tiexinprofile',
            name='qq',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
