# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160225_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiexinprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
