# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=toys.models.get_uuid, editable=False, max_length=36)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('sold_by_propose_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sold_by_propose_time', models.DateTimeField()),
                ('sold_by_accept_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sold_by_accept_time', models.DateTimeField(null=True)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sold_to_time', models.DateTimeField(null=True)),
                ('publish_time', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('num_images', models.PositiveSmallIntegerField(default=0)),
                ('image1', models.ImageField(null=True, upload_to=toys.models.get_fullsize_image_path)),
                ('image2', models.ImageField(null=True, upload_to=toys.models.get_fullsize_image_path)),
                ('image3', models.ImageField(null=True, upload_to=toys.models.get_fullsize_image_path)),
                ('image4', models.ImageField(null=True, upload_to=toys.models.get_fullsize_image_path)),
                ('image5', models.ImageField(null=True, upload_to=toys.models.get_fullsize_image_path)),
                ('image1_thumbnail', models.ImageField(null=True, upload_to=toys.models.get_thumbnail_image_path)),
                ('image2_thumbnail', models.ImageField(null=True, upload_to=toys.models.get_thumbnail_image_path)),
                ('image3_thumbnail', models.ImageField(null=True, upload_to=toys.models.get_thumbnail_image_path)),
                ('image4_thumbnail', models.ImageField(null=True, upload_to=toys.models.get_thumbnail_image_path)),
                ('image5_thumbnail', models.ImageField(null=True, upload_to=toys.models.get_thumbnail_image_path)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_by', to=settings.AUTH_USER_MODEL)),
                ('sold_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
