# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_toysource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toysource',
            name='original_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='toysource',
            name='purchase_time',
            field=models.CharField(max_length=50),
        ),
    ]
