# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_auto_20160223_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toysource',
            name='original_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
