# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_auto_20160225_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toysource',
            name='is_complete',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='toysource',
            name='is_final_quote_accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='toysource',
            name='is_instant_quote_accepted',
            field=models.NullBooleanField(),
        ),
    ]
