# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0010_toyinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toysource',
            options={'permissions': ('approve_toy', "Can approve a user's toy and finalize the quote")},
        ),
        migrations.RemoveField(
            model_name='toy',
            name='image5_thumbnail',
        ),
    ]
