# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywishes', '0002_auto_20160120_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishpopularity',
            old_name='n_comment',
            new_name='n_comments',
        ),
        migrations.RenameField(
            model_name='wishpopularity',
            old_name='n_forward',
            new_name='n_dislikes',
        ),
        migrations.RenameField(
            model_name='wishpopularity',
            old_name='n_like',
            new_name='n_forwards',
        ),
        migrations.RenameField(
            model_name='wishpopularity',
            old_name='n_view',
            new_name='n_likes',
        ),
        migrations.AddField(
            model_name='wishpopularity',
            name='n_views',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
